// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'conclusion',
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: ROS2',
          items: ['modules/module-1-ros2/chapter-1'],
        },
        {
          type: 'category',
          label: 'Module 2: Simulation',
          items: ['modules/module-2-simulation/chapter-1', 'modules/module-2-simulation/chapter-2'],
        },
        {
          type: 'category',
          label: 'Module 3: Nvidia Isaac',
          items: ['modules/module-3-nvidia-isaac/chapter-1', 'modules/module-3-nvidia-isaac/chapter-2'],
        },
        {
          type: 'category',
          label: 'Module 4: VLA',
          items: ['modules/module-4-vla/chapter-1', 'modules/module-4-vla/chapter-2'],
        },
      ],
    },
  
  ],
};

export default sidebars;
